/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as SearchRouteRouteImport } from './routes/search/route'
import { Route as ClientRouteRouteImport } from './routes/client/route'
import { Route as CategoriesRouteRouteImport } from './routes/categories/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactUsCountryRouteImport } from './routes/contact-us.$country'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as Char123LocaleChar125BlogRouteRouteImport } from './routes/{-$locale}/blog/route'
import { Route as CategoriesCategoryIdRouteRouteImport } from './routes/categories/$categoryId/route'
import { Route as AdminCategoriesRouteRouteImport } from './routes/admin/categories/route'
import { Route as ContactUsCountryCityRouteImport } from './routes/contact-us.$country.$city'
import { Route as AdminCategoriesCreateRouteImport } from './routes/admin/categories_.create'
import { Route as Char123LocaleChar125BlogTopicIdRouteRouteImport } from './routes/{-$locale}/blog/$topicId/route'
import { Route as CategoriesCategoryIdSubcategoryIdRouteRouteImport } from './routes/categories/$categoryId/$subcategoryId/route'
import { Route as ClientFilesSplatIndexRouteImport } from './routes/client/files/$/index'
import { Route as AdminCategoriesCategoryIdIndexRouteImport } from './routes/admin/categories/$categoryId/index'
import { Route as Char123LocaleChar125BlogTopicIdPostIdRouteRouteImport } from './routes/{-$locale}/blog/$topicId/$postId/route'
import { Route as CategoriesCategoryIdSubcategoryIdProductIdRouteRouteImport } from './routes/categories/$categoryId/$subcategoryId/$productId/route'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRouteRoute = SearchRouteRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRouteRoute = ClientRouteRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRouteRoute = CategoriesRouteRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsCountryRoute = ContactUsCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => ContactUsRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Char123LocaleChar125BlogRouteRoute =
  Char123LocaleChar125BlogRouteRouteImport.update({
    id: '/{-$locale}/blog',
    path: '/{-$locale}/blog',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesCategoryIdRouteRoute =
  CategoriesCategoryIdRouteRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => CategoriesRouteRoute,
  } as any)
const AdminCategoriesRouteRoute = AdminCategoriesRouteRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ContactUsCountryCityRoute = ContactUsCountryCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => ContactUsCountryRoute,
} as any)
const AdminCategoriesCreateRoute = AdminCategoriesCreateRouteImport.update({
  id: '/categories_/create',
  path: '/categories/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Char123LocaleChar125BlogTopicIdRouteRoute =
  Char123LocaleChar125BlogTopicIdRouteRouteImport.update({
    id: '/$topicId',
    path: '/$topicId',
    getParentRoute: () => Char123LocaleChar125BlogRouteRoute,
  } as any)
const CategoriesCategoryIdSubcategoryIdRouteRoute =
  CategoriesCategoryIdSubcategoryIdRouteRouteImport.update({
    id: '/$subcategoryId',
    path: '/$subcategoryId',
    getParentRoute: () => CategoriesCategoryIdRouteRoute,
  } as any)
const ClientFilesSplatIndexRoute = ClientFilesSplatIndexRouteImport.update({
  id: '/files/$/',
  path: '/files/$/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const AdminCategoriesCategoryIdIndexRoute =
  AdminCategoriesCategoryIdIndexRouteImport.update({
    id: '/$categoryId/',
    path: '/$categoryId/',
    getParentRoute: () => AdminCategoriesRouteRoute,
  } as any)
const Char123LocaleChar125BlogTopicIdPostIdRouteRoute =
  Char123LocaleChar125BlogTopicIdPostIdRouteRouteImport.update({
    id: '/$postId',
    path: '/$postId',
    getParentRoute: () => Char123LocaleChar125BlogTopicIdRouteRoute,
  } as any)
const CategoriesCategoryIdSubcategoryIdProductIdRouteRoute =
  CategoriesCategoryIdSubcategoryIdProductIdRouteRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => CategoriesCategoryIdSubcategoryIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/client': typeof ClientRouteRouteWithChildren
  '/search': typeof SearchRouteRoute
  '/contact-us': typeof ContactUsRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRouteRouteWithChildren
  '/categories/$categoryId': typeof CategoriesCategoryIdRouteRouteWithChildren
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogRouteRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/contact-us/$country': typeof ContactUsCountryRouteWithChildren
  '/categories/$categoryId/$subcategoryId': typeof CategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
  '/{-$locale}/blog/$topicId': typeof Char123LocaleChar125BlogTopicIdRouteRouteWithChildren
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/contact-us/$country/$city': typeof ContactUsCountryCityRoute
  '/categories/$categoryId/$subcategoryId/$productId': typeof CategoriesCategoryIdSubcategoryIdProductIdRouteRoute
  '/{-$locale}/blog/$topicId/$postId': typeof Char123LocaleChar125BlogTopicIdPostIdRouteRoute
  '/admin/categories/$categoryId': typeof AdminCategoriesCategoryIdIndexRoute
  '/client/files/$': typeof ClientFilesSplatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/client': typeof ClientRouteRouteWithChildren
  '/search': typeof SearchRouteRoute
  '/contact-us': typeof ContactUsRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRouteRouteWithChildren
  '/categories/$categoryId': typeof CategoriesCategoryIdRouteRouteWithChildren
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogRouteRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/contact-us/$country': typeof ContactUsCountryRouteWithChildren
  '/categories/$categoryId/$subcategoryId': typeof CategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
  '/{-$locale}/blog/$topicId': typeof Char123LocaleChar125BlogTopicIdRouteRouteWithChildren
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/contact-us/$country/$city': typeof ContactUsCountryCityRoute
  '/categories/$categoryId/$subcategoryId/$productId': typeof CategoriesCategoryIdSubcategoryIdProductIdRouteRoute
  '/{-$locale}/blog/$topicId/$postId': typeof Char123LocaleChar125BlogTopicIdPostIdRouteRoute
  '/admin/categories/$categoryId': typeof AdminCategoriesCategoryIdIndexRoute
  '/client/files/$': typeof ClientFilesSplatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/client': typeof ClientRouteRouteWithChildren
  '/search': typeof SearchRouteRoute
  '/contact-us': typeof ContactUsRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRouteRouteWithChildren
  '/categories/$categoryId': typeof CategoriesCategoryIdRouteRouteWithChildren
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogRouteRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/contact-us/$country': typeof ContactUsCountryRouteWithChildren
  '/categories/$categoryId/$subcategoryId': typeof CategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
  '/{-$locale}/blog/$topicId': typeof Char123LocaleChar125BlogTopicIdRouteRouteWithChildren
  '/admin/categories_/create': typeof AdminCategoriesCreateRoute
  '/contact-us/$country/$city': typeof ContactUsCountryCityRoute
  '/categories/$categoryId/$subcategoryId/$productId': typeof CategoriesCategoryIdSubcategoryIdProductIdRouteRoute
  '/{-$locale}/blog/$topicId/$postId': typeof Char123LocaleChar125BlogTopicIdPostIdRouteRoute
  '/admin/categories/$categoryId/': typeof AdminCategoriesCategoryIdIndexRoute
  '/client/files/$/': typeof ClientFilesSplatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/categories'
    | '/client'
    | '/search'
    | '/contact-us'
    | '/login'
    | '/admin/categories'
    | '/categories/$categoryId'
    | '/{-$locale}/blog'
    | '/admin/reports'
    | '/contact-us/$country'
    | '/categories/$categoryId/$subcategoryId'
    | '/{-$locale}/blog/$topicId'
    | '/admin/categories/create'
    | '/contact-us/$country/$city'
    | '/categories/$categoryId/$subcategoryId/$productId'
    | '/{-$locale}/blog/$topicId/$postId'
    | '/admin/categories/$categoryId'
    | '/client/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/categories'
    | '/client'
    | '/search'
    | '/contact-us'
    | '/login'
    | '/admin/categories'
    | '/categories/$categoryId'
    | '/{-$locale}/blog'
    | '/admin/reports'
    | '/contact-us/$country'
    | '/categories/$categoryId/$subcategoryId'
    | '/{-$locale}/blog/$topicId'
    | '/admin/categories/create'
    | '/contact-us/$country/$city'
    | '/categories/$categoryId/$subcategoryId/$productId'
    | '/{-$locale}/blog/$topicId/$postId'
    | '/admin/categories/$categoryId'
    | '/client/files/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/categories'
    | '/client'
    | '/search'
    | '/contact-us'
    | '/login'
    | '/admin/categories'
    | '/categories/$categoryId'
    | '/{-$locale}/blog'
    | '/admin/reports'
    | '/contact-us/$country'
    | '/categories/$categoryId/$subcategoryId'
    | '/{-$locale}/blog/$topicId'
    | '/admin/categories_/create'
    | '/contact-us/$country/$city'
    | '/categories/$categoryId/$subcategoryId/$productId'
    | '/{-$locale}/blog/$topicId/$postId'
    | '/admin/categories/$categoryId/'
    | '/client/files/$/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CategoriesRouteRoute: typeof CategoriesRouteRouteWithChildren
  ClientRouteRoute: typeof ClientRouteRouteWithChildren
  SearchRouteRoute: typeof SearchRouteRoute
  ContactUsRoute: typeof ContactUsRouteWithChildren
  LoginRoute: typeof LoginRoute
  Char123LocaleChar125BlogRouteRoute: typeof Char123LocaleChar125BlogRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us/$country': {
      id: '/contact-us/$country'
      path: '/$country'
      fullPath: '/contact-us/$country'
      preLoaderRoute: typeof ContactUsCountryRouteImport
      parentRoute: typeof ContactUsRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/{-$locale}/blog': {
      id: '/{-$locale}/blog'
      path: '/{-$locale}/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof Char123LocaleChar125BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteRouteImport
      parentRoute: typeof CategoriesRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/contact-us/$country/$city': {
      id: '/contact-us/$country/$city'
      path: '/$city'
      fullPath: '/contact-us/$country/$city'
      preLoaderRoute: typeof ContactUsCountryCityRouteImport
      parentRoute: typeof ContactUsCountryRoute
    }
    '/admin/categories_/create': {
      id: '/admin/categories_/create'
      path: '/categories/create'
      fullPath: '/admin/categories/create'
      preLoaderRoute: typeof AdminCategoriesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/{-$locale}/blog/$topicId': {
      id: '/{-$locale}/blog/$topicId'
      path: '/$topicId'
      fullPath: '/{-$locale}/blog/$topicId'
      preLoaderRoute: typeof Char123LocaleChar125BlogTopicIdRouteRouteImport
      parentRoute: typeof Char123LocaleChar125BlogRouteRoute
    }
    '/categories/$categoryId/$subcategoryId': {
      id: '/categories/$categoryId/$subcategoryId'
      path: '/$subcategoryId'
      fullPath: '/categories/$categoryId/$subcategoryId'
      preLoaderRoute: typeof CategoriesCategoryIdSubcategoryIdRouteRouteImport
      parentRoute: typeof CategoriesCategoryIdRouteRoute
    }
    '/client/files/$/': {
      id: '/client/files/$/'
      path: '/files/$'
      fullPath: '/client/files/$'
      preLoaderRoute: typeof ClientFilesSplatIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/admin/categories/$categoryId/': {
      id: '/admin/categories/$categoryId/'
      path: '/$categoryId'
      fullPath: '/admin/categories/$categoryId'
      preLoaderRoute: typeof AdminCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof AdminCategoriesRouteRoute
    }
    '/{-$locale}/blog/$topicId/$postId': {
      id: '/{-$locale}/blog/$topicId/$postId'
      path: '/$postId'
      fullPath: '/{-$locale}/blog/$topicId/$postId'
      preLoaderRoute: typeof Char123LocaleChar125BlogTopicIdPostIdRouteRouteImport
      parentRoute: typeof Char123LocaleChar125BlogTopicIdRouteRoute
    }
    '/categories/$categoryId/$subcategoryId/$productId': {
      id: '/categories/$categoryId/$subcategoryId/$productId'
      path: '/$productId'
      fullPath: '/categories/$categoryId/$subcategoryId/$productId'
      preLoaderRoute: typeof CategoriesCategoryIdSubcategoryIdProductIdRouteRouteImport
      parentRoute: typeof CategoriesCategoryIdSubcategoryIdRouteRoute
    }
  }
}

interface AdminCategoriesRouteRouteChildren {
  AdminCategoriesCategoryIdIndexRoute: typeof AdminCategoriesCategoryIdIndexRoute
}

const AdminCategoriesRouteRouteChildren: AdminCategoriesRouteRouteChildren = {
  AdminCategoriesCategoryIdIndexRoute: AdminCategoriesCategoryIdIndexRoute,
}

const AdminCategoriesRouteRouteWithChildren =
  AdminCategoriesRouteRoute._addFileChildren(AdminCategoriesRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminCategoriesRouteRoute: typeof AdminCategoriesRouteRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminCategoriesCreateRoute: typeof AdminCategoriesCreateRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesRouteRoute: AdminCategoriesRouteRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminCategoriesCreateRoute: AdminCategoriesCreateRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CategoriesCategoryIdSubcategoryIdRouteRouteChildren {
  CategoriesCategoryIdSubcategoryIdProductIdRouteRoute: typeof CategoriesCategoryIdSubcategoryIdProductIdRouteRoute
}

const CategoriesCategoryIdSubcategoryIdRouteRouteChildren: CategoriesCategoryIdSubcategoryIdRouteRouteChildren =
  {
    CategoriesCategoryIdSubcategoryIdProductIdRouteRoute:
      CategoriesCategoryIdSubcategoryIdProductIdRouteRoute,
  }

const CategoriesCategoryIdSubcategoryIdRouteRouteWithChildren =
  CategoriesCategoryIdSubcategoryIdRouteRoute._addFileChildren(
    CategoriesCategoryIdSubcategoryIdRouteRouteChildren,
  )

interface CategoriesCategoryIdRouteRouteChildren {
  CategoriesCategoryIdSubcategoryIdRouteRoute: typeof CategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
}

const CategoriesCategoryIdRouteRouteChildren: CategoriesCategoryIdRouteRouteChildren =
  {
    CategoriesCategoryIdSubcategoryIdRouteRoute:
      CategoriesCategoryIdSubcategoryIdRouteRouteWithChildren,
  }

const CategoriesCategoryIdRouteRouteWithChildren =
  CategoriesCategoryIdRouteRoute._addFileChildren(
    CategoriesCategoryIdRouteRouteChildren,
  )

interface CategoriesRouteRouteChildren {
  CategoriesCategoryIdRouteRoute: typeof CategoriesCategoryIdRouteRouteWithChildren
}

const CategoriesRouteRouteChildren: CategoriesRouteRouteChildren = {
  CategoriesCategoryIdRouteRoute: CategoriesCategoryIdRouteRouteWithChildren,
}

const CategoriesRouteRouteWithChildren = CategoriesRouteRoute._addFileChildren(
  CategoriesRouteRouteChildren,
)

interface ClientRouteRouteChildren {
  ClientFilesSplatIndexRoute: typeof ClientFilesSplatIndexRoute
}

const ClientRouteRouteChildren: ClientRouteRouteChildren = {
  ClientFilesSplatIndexRoute: ClientFilesSplatIndexRoute,
}

const ClientRouteRouteWithChildren = ClientRouteRoute._addFileChildren(
  ClientRouteRouteChildren,
)

interface ContactUsCountryRouteChildren {
  ContactUsCountryCityRoute: typeof ContactUsCountryCityRoute
}

const ContactUsCountryRouteChildren: ContactUsCountryRouteChildren = {
  ContactUsCountryCityRoute: ContactUsCountryCityRoute,
}

const ContactUsCountryRouteWithChildren =
  ContactUsCountryRoute._addFileChildren(ContactUsCountryRouteChildren)

interface ContactUsRouteChildren {
  ContactUsCountryRoute: typeof ContactUsCountryRouteWithChildren
}

const ContactUsRouteChildren: ContactUsRouteChildren = {
  ContactUsCountryRoute: ContactUsCountryRouteWithChildren,
}

const ContactUsRouteWithChildren = ContactUsRoute._addFileChildren(
  ContactUsRouteChildren,
)

interface Char123LocaleChar125BlogTopicIdRouteRouteChildren {
  Char123LocaleChar125BlogTopicIdPostIdRouteRoute: typeof Char123LocaleChar125BlogTopicIdPostIdRouteRoute
}

const Char123LocaleChar125BlogTopicIdRouteRouteChildren: Char123LocaleChar125BlogTopicIdRouteRouteChildren =
  {
    Char123LocaleChar125BlogTopicIdPostIdRouteRoute:
      Char123LocaleChar125BlogTopicIdPostIdRouteRoute,
  }

const Char123LocaleChar125BlogTopicIdRouteRouteWithChildren =
  Char123LocaleChar125BlogTopicIdRouteRoute._addFileChildren(
    Char123LocaleChar125BlogTopicIdRouteRouteChildren,
  )

interface Char123LocaleChar125BlogRouteRouteChildren {
  Char123LocaleChar125BlogTopicIdRouteRoute: typeof Char123LocaleChar125BlogTopicIdRouteRouteWithChildren
}

const Char123LocaleChar125BlogRouteRouteChildren: Char123LocaleChar125BlogRouteRouteChildren =
  {
    Char123LocaleChar125BlogTopicIdRouteRoute:
      Char123LocaleChar125BlogTopicIdRouteRouteWithChildren,
  }

const Char123LocaleChar125BlogRouteRouteWithChildren =
  Char123LocaleChar125BlogRouteRoute._addFileChildren(
    Char123LocaleChar125BlogRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CategoriesRouteRoute: CategoriesRouteRouteWithChildren,
  ClientRouteRoute: ClientRouteRouteWithChildren,
  SearchRouteRoute: SearchRouteRoute,
  ContactUsRoute: ContactUsRouteWithChildren,
  LoginRoute: LoginRoute,
  Char123LocaleChar125BlogRouteRoute:
    Char123LocaleChar125BlogRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
