/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as CategoriesRouteRouteImport } from './routes/categories/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as ProductsFeaturedRouteImport } from './routes/products/featured'
import { Route as ContactUsCountryRouteImport } from './routes/contact-us.$country'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as Char123LocaleChar125BlogRouteRouteImport } from './routes/{-$locale}/blog/route'
import { Route as ProductsSearchRouteRouteImport } from './routes/products/search/route'
import { Route as ProductsProductIdRouteRouteImport } from './routes/products/$productId/route'
import { Route as CategoriesCategoryIdRouteRouteImport } from './routes/categories/$categoryId/route'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountFilesIndexRouteImport } from './routes/account/files/index'
import { Route as ProductsProductIdReviewRouteImport } from './routes/products/$productId/review'
import { Route as ContactUsCountryCityRouteImport } from './routes/contact-us.$country.$city'
import { Route as Char123LocaleChar125BlogCategoryIdRouteRouteImport } from './routes/{-$locale}/blog/$categoryId/route'
import { Route as CategoriesCategoryIdSubcategoryIdRouteRouteImport } from './routes/categories/$categoryId/$subcategoryId/route'
import { Route as AdminProductsCreateIndexRouteImport } from './routes/admin/products/create/index'
import { Route as AdminProductsProductIdIndexRouteImport } from './routes/admin/products/$productId/index'
import { Route as AdminCategoriesCreateIndexRouteImport } from './routes/admin/categories/create/index'
import { Route as AdminCategoriesCategoryIdIndexRouteImport } from './routes/admin/categories/$categoryId/index'
import { Route as AccountOrdersOrderIdIndexRouteImport } from './routes/account/orders/$orderId/index'
import { Route as AccountFilesSplatIndexRouteImport } from './routes/account/files/$/index'
import { Route as Char123LocaleChar125BlogCategoryIdProductIdRouteRouteImport } from './routes/{-$locale}/blog/$categoryId/$productId/route'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRouteRoute = CategoriesRouteRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFeaturedRoute = ProductsFeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ContactUsCountryRoute = ContactUsCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => ContactUsRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125BlogRouteRoute =
  Char123LocaleChar125BlogRouteRouteImport.update({
    id: '/{-$locale}/blog',
    path: '/{-$locale}/blog',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsSearchRouteRoute = ProductsSearchRouteRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsProductIdRouteRoute = ProductsProductIdRouteRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const CategoriesCategoryIdRouteRoute =
  CategoriesCategoryIdRouteRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => CategoriesRouteRoute,
  } as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/admin/categories/',
  path: '/admin/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountFilesIndexRoute = AccountFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const ProductsProductIdReviewRoute = ProductsProductIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ProductsProductIdRouteRoute,
} as any)
const ContactUsCountryCityRoute = ContactUsCountryCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => ContactUsCountryRoute,
} as any)
const Char123LocaleChar125BlogCategoryIdRouteRoute =
  Char123LocaleChar125BlogCategoryIdRouteRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => Char123LocaleChar125BlogRouteRoute,
  } as any)
const CategoriesCategoryIdSubcategoryIdRouteRoute =
  CategoriesCategoryIdSubcategoryIdRouteRouteImport.update({
    id: '/$subcategoryId',
    path: '/$subcategoryId',
    getParentRoute: () => CategoriesCategoryIdRouteRoute,
  } as any)
const AdminProductsCreateIndexRoute =
  AdminProductsCreateIndexRouteImport.update({
    id: '/admin/products/create/',
    path: '/admin/products/create/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProductsProductIdIndexRoute =
  AdminProductsProductIdIndexRouteImport.update({
    id: '/admin/products/$productId/',
    path: '/admin/products/$productId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCategoriesCreateIndexRoute =
  AdminCategoriesCreateIndexRouteImport.update({
    id: '/admin/categories/create/',
    path: '/admin/categories/create/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCategoriesCategoryIdIndexRoute =
  AdminCategoriesCategoryIdIndexRouteImport.update({
    id: '/admin/categories/$categoryId/',
    path: '/admin/categories/$categoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountOrdersOrderIdIndexRoute =
  AccountOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => AccountRouteRoute,
  } as any)
const AccountFilesSplatIndexRoute = AccountFilesSplatIndexRouteImport.update({
  id: '/files/$/',
  path: '/files/$/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const Char123LocaleChar125BlogCategoryIdProductIdRouteRoute =
  Char123LocaleChar125BlogCategoryIdProductIdRouteRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => Char123LocaleChar125BlogCategoryIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/account': typeof AccountRouteRouteWithChildren
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRouteWithChildren
  '/login': typeof LoginRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRouteRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRouteRouteWithChildren
  '/products/search': typeof ProductsSearchRouteRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogRouteRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/contact-us/$country': typeof ContactUsCountryRouteWithChildren
  '/products/featured': typeof ProductsFeaturedRoute
  '/categories/$categoryId/$subcategoryId': typeof CategoriesCategoryIdSubcategoryIdRouteRoute
  '/{-$locale}/blog/$categoryId': typeof Char123LocaleChar125BlogCategoryIdRouteRouteWithChildren
  '/contact-us/$country/$city': typeof ContactUsCountryCityRoute
  '/products/$productId/review': typeof ProductsProductIdReviewRoute
  '/account/files': typeof AccountFilesIndexRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/{-$locale}/blog/$categoryId/$productId': typeof Char123LocaleChar125BlogCategoryIdProductIdRouteRoute
  '/account/files/$': typeof AccountFilesSplatIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdIndexRoute
  '/admin/categories/$categoryId': typeof AdminCategoriesCategoryIdIndexRoute
  '/admin/categories/create': typeof AdminCategoriesCreateIndexRoute
  '/admin/products/$productId': typeof AdminProductsProductIdIndexRoute
  '/admin/products/create': typeof AdminProductsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/account': typeof AccountRouteRouteWithChildren
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRouteWithChildren
  '/login': typeof LoginRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRouteRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRouteRouteWithChildren
  '/products/search': typeof ProductsSearchRouteRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogRouteRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/contact-us/$country': typeof ContactUsCountryRouteWithChildren
  '/products/featured': typeof ProductsFeaturedRoute
  '/categories/$categoryId/$subcategoryId': typeof CategoriesCategoryIdSubcategoryIdRouteRoute
  '/{-$locale}/blog/$categoryId': typeof Char123LocaleChar125BlogCategoryIdRouteRouteWithChildren
  '/contact-us/$country/$city': typeof ContactUsCountryCityRoute
  '/products/$productId/review': typeof ProductsProductIdReviewRoute
  '/account/files': typeof AccountFilesIndexRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/{-$locale}/blog/$categoryId/$productId': typeof Char123LocaleChar125BlogCategoryIdProductIdRouteRoute
  '/account/files/$': typeof AccountFilesSplatIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdIndexRoute
  '/admin/categories/$categoryId': typeof AdminCategoriesCategoryIdIndexRoute
  '/admin/categories/create': typeof AdminCategoriesCreateIndexRoute
  '/admin/products/$productId': typeof AdminProductsProductIdIndexRoute
  '/admin/products/create': typeof AdminProductsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/account': typeof AccountRouteRouteWithChildren
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRouteWithChildren
  '/login': typeof LoginRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRouteRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRouteRouteWithChildren
  '/products/search': typeof ProductsSearchRouteRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogRouteRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/contact-us/$country': typeof ContactUsCountryRouteWithChildren
  '/products/featured': typeof ProductsFeaturedRoute
  '/categories/$categoryId/$subcategoryId': typeof CategoriesCategoryIdSubcategoryIdRouteRoute
  '/{-$locale}/blog/$categoryId': typeof Char123LocaleChar125BlogCategoryIdRouteRouteWithChildren
  '/contact-us/$country/$city': typeof ContactUsCountryCityRoute
  '/products/$productId/review': typeof ProductsProductIdReviewRoute
  '/account/files/': typeof AccountFilesIndexRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/{-$locale}/blog/$categoryId/$productId': typeof Char123LocaleChar125BlogCategoryIdProductIdRouteRoute
  '/account/files/$/': typeof AccountFilesSplatIndexRoute
  '/account/orders/$orderId/': typeof AccountOrdersOrderIdIndexRoute
  '/admin/categories/$categoryId/': typeof AdminCategoriesCategoryIdIndexRoute
  '/admin/categories/create/': typeof AdminCategoriesCreateIndexRoute
  '/admin/products/$productId/': typeof AdminProductsProductIdIndexRoute
  '/admin/products/create/': typeof AdminProductsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account'
    | '/categories'
    | '/products'
    | '/about'
    | '/contact-us'
    | '/login'
    | '/categories/$categoryId'
    | '/products/$productId'
    | '/products/search'
    | '/{-$locale}/blog'
    | '/admin/reports'
    | '/contact-us/$country'
    | '/products/featured'
    | '/categories/$categoryId/$subcategoryId'
    | '/{-$locale}/blog/$categoryId'
    | '/contact-us/$country/$city'
    | '/products/$productId/review'
    | '/account/files'
    | '/account/orders'
    | '/admin/categories'
    | '/{-$locale}/blog/$categoryId/$productId'
    | '/account/files/$'
    | '/account/orders/$orderId'
    | '/admin/categories/$categoryId'
    | '/admin/categories/create'
    | '/admin/products/$productId'
    | '/admin/products/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/categories'
    | '/products'
    | '/about'
    | '/contact-us'
    | '/login'
    | '/categories/$categoryId'
    | '/products/$productId'
    | '/products/search'
    | '/{-$locale}/blog'
    | '/admin/reports'
    | '/contact-us/$country'
    | '/products/featured'
    | '/categories/$categoryId/$subcategoryId'
    | '/{-$locale}/blog/$categoryId'
    | '/contact-us/$country/$city'
    | '/products/$productId/review'
    | '/account/files'
    | '/account/orders'
    | '/admin/categories'
    | '/{-$locale}/blog/$categoryId/$productId'
    | '/account/files/$'
    | '/account/orders/$orderId'
    | '/admin/categories/$categoryId'
    | '/admin/categories/create'
    | '/admin/products/$productId'
    | '/admin/products/create'
  id:
    | '__root__'
    | '/account'
    | '/categories'
    | '/products'
    | '/about'
    | '/contact-us'
    | '/login'
    | '/categories/$categoryId'
    | '/products/$productId'
    | '/products/search'
    | '/{-$locale}/blog'
    | '/admin/reports'
    | '/contact-us/$country'
    | '/products/featured'
    | '/categories/$categoryId/$subcategoryId'
    | '/{-$locale}/blog/$categoryId'
    | '/contact-us/$country/$city'
    | '/products/$productId/review'
    | '/account/files/'
    | '/account/orders/'
    | '/admin/categories/'
    | '/{-$locale}/blog/$categoryId/$productId'
    | '/account/files/$/'
    | '/account/orders/$orderId/'
    | '/admin/categories/$categoryId/'
    | '/admin/categories/create/'
    | '/admin/products/$productId/'
    | '/admin/products/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  CategoriesRouteRoute: typeof CategoriesRouteRouteWithChildren
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactUsRoute: typeof ContactUsRouteWithChildren
  LoginRoute: typeof LoginRoute
  Char123LocaleChar125BlogRouteRoute: typeof Char123LocaleChar125BlogRouteRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminCategoriesCategoryIdIndexRoute: typeof AdminCategoriesCategoryIdIndexRoute
  AdminCategoriesCreateIndexRoute: typeof AdminCategoriesCreateIndexRoute
  AdminProductsProductIdIndexRoute: typeof AdminProductsProductIdIndexRoute
  AdminProductsCreateIndexRoute: typeof AdminProductsCreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/featured': {
      id: '/products/featured'
      path: '/featured'
      fullPath: '/products/featured'
      preLoaderRoute: typeof ProductsFeaturedRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/contact-us/$country': {
      id: '/contact-us/$country'
      path: '/$country'
      fullPath: '/contact-us/$country'
      preLoaderRoute: typeof ContactUsCountryRouteImport
      parentRoute: typeof ContactUsRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/blog': {
      id: '/{-$locale}/blog'
      path: '/{-$locale}/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof Char123LocaleChar125BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/search': {
      id: '/products/search'
      path: '/search'
      fullPath: '/products/search'
      preLoaderRoute: typeof ProductsSearchRouteRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteRouteImport
      parentRoute: typeof CategoriesRouteRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/files/': {
      id: '/account/files/'
      path: '/files'
      fullPath: '/account/files'
      preLoaderRoute: typeof AccountFilesIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/products/$productId/review': {
      id: '/products/$productId/review'
      path: '/review'
      fullPath: '/products/$productId/review'
      preLoaderRoute: typeof ProductsProductIdReviewRouteImport
      parentRoute: typeof ProductsProductIdRouteRoute
    }
    '/contact-us/$country/$city': {
      id: '/contact-us/$country/$city'
      path: '/$city'
      fullPath: '/contact-us/$country/$city'
      preLoaderRoute: typeof ContactUsCountryCityRouteImport
      parentRoute: typeof ContactUsCountryRoute
    }
    '/{-$locale}/blog/$categoryId': {
      id: '/{-$locale}/blog/$categoryId'
      path: '/$categoryId'
      fullPath: '/{-$locale}/blog/$categoryId'
      preLoaderRoute: typeof Char123LocaleChar125BlogCategoryIdRouteRouteImport
      parentRoute: typeof Char123LocaleChar125BlogRouteRoute
    }
    '/categories/$categoryId/$subcategoryId': {
      id: '/categories/$categoryId/$subcategoryId'
      path: '/$subcategoryId'
      fullPath: '/categories/$categoryId/$subcategoryId'
      preLoaderRoute: typeof CategoriesCategoryIdSubcategoryIdRouteRouteImport
      parentRoute: typeof CategoriesCategoryIdRouteRoute
    }
    '/admin/products/create/': {
      id: '/admin/products/create/'
      path: '/admin/products/create'
      fullPath: '/admin/products/create'
      preLoaderRoute: typeof AdminProductsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$productId/': {
      id: '/admin/products/$productId/'
      path: '/admin/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories/create/': {
      id: '/admin/categories/create/'
      path: '/admin/categories/create'
      fullPath: '/admin/categories/create'
      preLoaderRoute: typeof AdminCategoriesCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories/$categoryId/': {
      id: '/admin/categories/$categoryId/'
      path: '/admin/categories/$categoryId'
      fullPath: '/admin/categories/$categoryId'
      preLoaderRoute: typeof AdminCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$orderId/': {
      id: '/account/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/files/$/': {
      id: '/account/files/$/'
      path: '/files/$'
      fullPath: '/account/files/$'
      preLoaderRoute: typeof AccountFilesSplatIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/{-$locale}/blog/$categoryId/$productId': {
      id: '/{-$locale}/blog/$categoryId/$productId'
      path: '/$productId'
      fullPath: '/{-$locale}/blog/$categoryId/$productId'
      preLoaderRoute: typeof Char123LocaleChar125BlogCategoryIdProductIdRouteRouteImport
      parentRoute: typeof Char123LocaleChar125BlogCategoryIdRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountFilesIndexRoute: typeof AccountFilesIndexRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
  AccountFilesSplatIndexRoute: typeof AccountFilesSplatIndexRoute
  AccountOrdersOrderIdIndexRoute: typeof AccountOrdersOrderIdIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountFilesIndexRoute: AccountFilesIndexRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
  AccountFilesSplatIndexRoute: AccountFilesSplatIndexRoute,
  AccountOrdersOrderIdIndexRoute: AccountOrdersOrderIdIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface CategoriesCategoryIdRouteRouteChildren {
  CategoriesCategoryIdSubcategoryIdRouteRoute: typeof CategoriesCategoryIdSubcategoryIdRouteRoute
}

const CategoriesCategoryIdRouteRouteChildren: CategoriesCategoryIdRouteRouteChildren =
  {
    CategoriesCategoryIdSubcategoryIdRouteRoute:
      CategoriesCategoryIdSubcategoryIdRouteRoute,
  }

const CategoriesCategoryIdRouteRouteWithChildren =
  CategoriesCategoryIdRouteRoute._addFileChildren(
    CategoriesCategoryIdRouteRouteChildren,
  )

interface CategoriesRouteRouteChildren {
  CategoriesCategoryIdRouteRoute: typeof CategoriesCategoryIdRouteRouteWithChildren
}

const CategoriesRouteRouteChildren: CategoriesRouteRouteChildren = {
  CategoriesCategoryIdRouteRoute: CategoriesCategoryIdRouteRouteWithChildren,
}

const CategoriesRouteRouteWithChildren = CategoriesRouteRoute._addFileChildren(
  CategoriesRouteRouteChildren,
)

interface ProductsProductIdRouteRouteChildren {
  ProductsProductIdReviewRoute: typeof ProductsProductIdReviewRoute
}

const ProductsProductIdRouteRouteChildren: ProductsProductIdRouteRouteChildren =
  {
    ProductsProductIdReviewRoute: ProductsProductIdReviewRoute,
  }

const ProductsProductIdRouteRouteWithChildren =
  ProductsProductIdRouteRoute._addFileChildren(
    ProductsProductIdRouteRouteChildren,
  )

interface ProductsRouteRouteChildren {
  ProductsProductIdRouteRoute: typeof ProductsProductIdRouteRouteWithChildren
  ProductsSearchRouteRoute: typeof ProductsSearchRouteRoute
  ProductsFeaturedRoute: typeof ProductsFeaturedRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsProductIdRouteRoute: ProductsProductIdRouteRouteWithChildren,
  ProductsSearchRouteRoute: ProductsSearchRouteRoute,
  ProductsFeaturedRoute: ProductsFeaturedRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

interface ContactUsCountryRouteChildren {
  ContactUsCountryCityRoute: typeof ContactUsCountryCityRoute
}

const ContactUsCountryRouteChildren: ContactUsCountryRouteChildren = {
  ContactUsCountryCityRoute: ContactUsCountryCityRoute,
}

const ContactUsCountryRouteWithChildren =
  ContactUsCountryRoute._addFileChildren(ContactUsCountryRouteChildren)

interface ContactUsRouteChildren {
  ContactUsCountryRoute: typeof ContactUsCountryRouteWithChildren
}

const ContactUsRouteChildren: ContactUsRouteChildren = {
  ContactUsCountryRoute: ContactUsCountryRouteWithChildren,
}

const ContactUsRouteWithChildren = ContactUsRoute._addFileChildren(
  ContactUsRouteChildren,
)

interface Char123LocaleChar125BlogCategoryIdRouteRouteChildren {
  Char123LocaleChar125BlogCategoryIdProductIdRouteRoute: typeof Char123LocaleChar125BlogCategoryIdProductIdRouteRoute
}

const Char123LocaleChar125BlogCategoryIdRouteRouteChildren: Char123LocaleChar125BlogCategoryIdRouteRouteChildren =
  {
    Char123LocaleChar125BlogCategoryIdProductIdRouteRoute:
      Char123LocaleChar125BlogCategoryIdProductIdRouteRoute,
  }

const Char123LocaleChar125BlogCategoryIdRouteRouteWithChildren =
  Char123LocaleChar125BlogCategoryIdRouteRoute._addFileChildren(
    Char123LocaleChar125BlogCategoryIdRouteRouteChildren,
  )

interface Char123LocaleChar125BlogRouteRouteChildren {
  Char123LocaleChar125BlogCategoryIdRouteRoute: typeof Char123LocaleChar125BlogCategoryIdRouteRouteWithChildren
}

const Char123LocaleChar125BlogRouteRouteChildren: Char123LocaleChar125BlogRouteRouteChildren =
  {
    Char123LocaleChar125BlogCategoryIdRouteRoute:
      Char123LocaleChar125BlogCategoryIdRouteRouteWithChildren,
  }

const Char123LocaleChar125BlogRouteRouteWithChildren =
  Char123LocaleChar125BlogRouteRoute._addFileChildren(
    Char123LocaleChar125BlogRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AccountRouteRoute: AccountRouteRouteWithChildren,
  CategoriesRouteRoute: CategoriesRouteRouteWithChildren,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactUsRoute: ContactUsRouteWithChildren,
  LoginRoute: LoginRoute,
  Char123LocaleChar125BlogRouteRoute:
    Char123LocaleChar125BlogRouteRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminCategoriesCategoryIdIndexRoute: AdminCategoriesCategoryIdIndexRoute,
  AdminCategoriesCreateIndexRoute: AdminCategoriesCreateIndexRoute,
  AdminProductsProductIdIndexRoute: AdminProductsProductIdIndexRoute,
  AdminProductsCreateIndexRoute: AdminProductsCreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
